[build]
publish = "docs/public"
command = "cd docs && hugo --gc --minify --themesDir ../.. -b ${DEPLOY_PRIME_URL}"

# Always trigger a rebuild, even if the files haven't changed.
# See https://docs.netlify.com/configure-builds/file-based-configuration/#ignore-builds
ignore = "false"

[build.environment]
HUGO_VERSION = "0.147.7"
GO_VERSION = "1.24.3"
NODE_VERSION = "22.16.0"
